export const INPUT_SELECTOR_NAME = 'input[name="name"]'
export const INPUT_SELECTOR_EMAIL = 'input[type="email"]'
export const INPUT_SELECTOR_PWD = 'input[name="password"]'
export const INPUT_SELECTOR_PWD_CONFIRM = 'input[name="password-confirmation"]'
export const CLASS_BTN_SELECTOR_SUBMIT = '.button-submit'
